// solid-app2/src/index.tsx
/* @refresh reload */
import { render } from 'solid-js/web';
import { Router, Routes, Route } from "solid-app-router"
import './index.css';
import App2 from './App2';

import CreateObjectSignalTest from './createSignalObject/Development'

render(() => 
<Router>
  <Routes>
    <Route path="/App2" element={<App2/>} />
    <Route path="/CreateObjectSignalTest" element={<CreateObjectSignalTest/>} />
    <Route path="/*" element={<h1>404</h1>}/>
  </Routes>
</Router>, document.getElementById('root') as HTMLElement);

// react-app/src/index.js
import React from 'react';
import ReactDOM from 'react-dom/client';
import { BrowserRouter, Routes, Route} from "react-router-dom";
import './index.css';

import Refs from './test/ElementReferences.jsx';

const root = ReactDOM.createRoot(document.getElementById('root'));
root.render(
    <React.StrictMode>
        <BrowserRouter>
            <Routes>
                <Route path="/references" element={<Refs />} />
            </Routes>
        </BrowserRouter>
    </React.StrictMode>
);
